name: thepuppyplace_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+19

# flutter clean && flutter pub get && cd ios && pod install && cd .. && fltuter build apk

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  email_validator: ^2.0.1
  intl: ^0.17.0
  image_picker: ^0.8.4+8
  image_cropper: ^3.0.0
  fluttertoast: ^8.0.8
  flutter_slidable: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  package_info_plus: ^1.3.0
  firebase_messaging: ^13.0.2
  flutter_local_notifications: ^11.0.0
  firebase_core: ^1.12.0
  flutter_svg: ^1.0.3
  animations: ^2.0.2
  pin_code_fields: ^7.3.0
  dot_navigation_bar: ^1.0.1+3
  animated_bottom_navigation_bar: ^1.1.0
  lottie: ^1.2.2
  sqflite: ^2.0.2
  path: ^1.8.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  multi_image_picker2: ^5.0.02
  url_launcher: ^6.1.0
  flutter_launcher_icons: ^0.10.0
  photo_view:
    git: https://github.com/bluefireteam/photo_view.git
  google_sign_in: ^5.3.1
  sign_in_with_apple: ^4.1.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  kakao_flutter_sdk: ^1.1.1
  kakao_flutter_sdk_link: ^1.1.1
  percent_indicator: ^4.2.2
  flutter_linkify: ^5.0.2
  equatable: ^2.0.5
  firebase_dynamic_links: ^4.3.7
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svg/
    - assets/jpeg/
    - assets/png/
    - assets/fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Tmoney
      fonts:
        - asset: assets/fonts/TmoneyRoundWindRegular.ttf
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_logo.png"

# 아이콘 설정
# flutter pub add flutter_launcher_icons && flutter pub get
# flutter_icons:
# android: "launcher_icon"
# ios: true
# image_path: “<logo path>”
# flutter pub run flutter_launcher_icons:main