name: thepuppyplace_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  email_validator: ^2.0.1
  intl: ^0.17.0
  image_picker: ^0.8.4+8
  image_cropper: ^1.4.1
  fluttertoast: ^8.0.8
  flutter_slidable: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  package_info_plus: ^1.3.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.3.2
  firebase_core: ^1.12.0
  flutter_svg: ^1.0.3
  animations: ^2.0.2
  pin_code_fields: ^7.3.0
  dot_navigation_bar: ^1.0.1+3
  animated_bottom_navigation_bar: ^0.3.2
  lottie: ^1.2.2
  sqflite: ^2.0.2
  path: ^1.8.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  multi_image_picker2: ^5.0.02
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/jpeg/
    - assets/png/
    - assets/fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Tmoney
      fonts:
        - asset: assets/fonts/TmoneyRoundWindRegular.ttf
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle.ttf